### ISSUE TITLE
一定要sls工具才能部署的么？

### ISSUE THREAD

**Issue by mengdu** [serverless-components/tencent-express#18]
```
 serverless deploy
```

error:
```
 error:
  Error: "component" input is required to run custom methods
    at Proxy.<anonymous> (D:\software\node-v10.16.0\node_modules\serverless\node_modules\@serverless\template\utils.js:350:13)
    at Object.runComponents (D:\software\node-v10.16.0\node_modules\serverless\node_modules\@serverless\cli\src\index.js:209:40)
```

**Comment by tinafangkunding** [comment]
您好，辛苦执行 serverless 命令试一下呢
